// Raw consensus ADP snapshot (standard offense-relevant positions + IDP noise
// to be filtered out), sourced from public fantasy ADP aggregators, late
// August 2026. Format: [marketRank, "Player Name", "TEAM", "POS"]
// POS values include non-fantasy-relevant IDP tags (DE, LB, S, DT, CB) which
// the build script filters out, since this league only rosters team D/ST.
export const RAW_ADP = [
  [1, "Jahmyr Gibbs", "DET", "RB"],
  [2, "Bijan Robinson", "ATL", "RB"],
  [3, "Ja'Marr Chase", "CIN", "WR"],
  [4, "Puka Nacua", "LAR", "WR"],
  [5, "Christian McCaffrey", "SF", "RB"],
  [6, "Jaxon Smith-Njigba", "SEA", "WR"],
  [7, "Jonathan Taylor", "IND", "RB"],
  [8, "Amon-Ra St. Brown", "DET", "WR"],
  [9, "James Cook", "BUF", "RB"],
  [10, "Justin Jefferson", "MIN", "WR"],
  [11, "CeeDee Lamb", "DAL", "WR"],
  [12, "Chase Brown", "CIN", "RB"],
  [13, "De'Von Achane", "MIA", "RB"],
  [14, "Saquon Barkley", "PHI", "RB"],
  [15, "Omarion Hampton", "LAC", "RB"],
  [16, "Kenneth Walker", "KC", "RB"],
  [17, "A.J. Brown", "NE", "WR"],
  [18, "Ashton Jeanty", "LV", "RB"],
  [19, "Derrick Henry", "BAL", "RB"],
  [20, "Brock Bowers", "LV", "TE"],
  [21, "Drake London", "ATL", "WR"],
  [22, "Nico Collins", "HOU", "WR"],
  [23, "Malik Nabers", "NYG", "WR"],
  [24, "Chris Olave", "NO", "WR"],
  [25, "Trey McBride", "ARI", "TE"],
  [26, "George Pickens", "DAL", "WR"],
  [27, "Kyren Williams", "LAR", "RB"],
  [28, "DeVonta Smith", "PHI", "WR"],
  [29, "Rashee Rice", "KC", "WR"],
  [30, "Javonte Williams", "DAL", "RB"],
  [31, "Josh Allen", "BUF", "QB"],
  [32, "Breece Hall", "NYJ", "RB"],
  [33, "Jeremiyah Love", "ARI", "RB"],
  [34, "Zay Flowers", "BAL", "WR"],
  [35, "Travis Etienne", "NO", "RB"],
  [36, "Tetairoa McMillan", "CAR", "WR"],
  [37, "Tee Higgins", "CIN", "WR"],
  [38, "Garrett Wilson", "NYJ", "WR"],
  [39, "Emeka Egbuka", "TB", "WR"],
  [40, "Cam Skattebo", "NYG", "RB"],
  [41, "Colston Loveland", "CHI", "TE"],
  [42, "Jaylen Waddle", "DEN", "WR"],
  [43, "D'Andre Swift", "CHI", "RB"],
  [44, "Parker Washington", "JAX", "WR"],
  [45, "Davante Adams", "LAR", "WR"],
  [46, "Lamar Jackson", "BAL", "QB"],
  [47, "David Montgomery", "HOU", "RB"],
  [48, "Quinshon Judkins", "CLE", "RB"],
  [49, "Terry McLaurin", "WAS", "WR"],
  [50, "Luther Burden", "CHI", "WR"],
  [51, "Josh Jacobs", "GB", "RB"],
  [52, "DJ Moore", "BUF", "WR"],
  [53, "Tyler Warren", "IND", "TE"],
  [54, "Joe Burrow", "CIN", "QB"],
  [55, "Drake Maye", "NE", "QB"],
  [56, "Ladd McConkey", "LAC", "WR"],
  [57, "Bucky Irving", "TB", "RB"],
  [58, "Rhamondre Stevenson", "NE", "RB"],
  [59, "Jameson Williams", "DET", "WR"],
  [60, "Bhayshul Tuten", "JAX", "RB"],
  [61, "Christian Watson", "GB", "WR"],
  [62, "TreVeyon Henderson", "NE", "RB"],
  [63, "Rome Odunze", "CHI", "WR"],
  [64, "Jadarian Price", "SEA", "RB"],
  [65, "Mike Evans", "SF", "WR"],
  [66, "Jonathon Brooks", "CAR", "RB"],
  [67, "Jayden Daniels", "WAS", "QB"],
  [68, "Carnell Tate", "TEN", "WR"],
  [69, "De'Zhaun Stribling", "SF", "WR"],
  [70, "Jalen Hurts", "PHI", "QB"],
  [71, "Caleb Williams", "CHI", "QB"],
  [72, "Jaylen Warren", "PIT", "RB"],
  [73, "Brian Thomas", "JAX", "WR"],
  [74, "Marvin Harrison", "ARI", "WR"],
  [75, "Tucker Kraft", "GB", "TE"],
  [76, "Harold Fannin", "CLE", "TE"],
  [77, "Courtland Sutton", "DEN", "WR"],
  [78, "Tony Pollard", "TEN", "RB"],
  [79, "Dak Prescott", "DAL", "QB"],
  [80, "RJ Harvey", "DEN", "RB"],
  [81, "DK Metcalf", "PIT", "WR"],
  [82, "Kyle Pitts", "ATL", "TE"],
  [83, "Stefon Diggs", "WAS", "WR"],
  [84, "MarShawn Lloyd", "GB", "RB"],
  [85, "Rico Dowdle", "PIT", "RB"],
  [86, "Sam LaPorta", "DET", "TE"],
  [87, "Chris Godwin", "TB", "WR"],
  [88, "Justin Herbert", "LAC", "QB"],
  [89, "Rachaad White", "WAS", "RB"],
  [90, "Trevor Lawrence", "JAX", "QB"],
  [91, "Quentin Johnston", "LAC", "WR"],
  [92, "Chuba Hubbard", "CAR", "RB"],
  [93, "Michael Wilson", "ARI", "WR"],
  [94, "J.K. Dobbins", "DEN", "RB"],
  [95, "Matthew Stafford", "LAR", "QB"],
  [96, "Michael Pittman", "PIT", "WR"],
  [97, "Blake Corum", "LAR", "RB"],
  [98, "Makai Lemon", "PHI", "WR"],
  [99, "Josh Downs", "IND", "WR"],
  [100, "George Kittle", "SF", "TE"],
  [101, "Kenny Gainwell", "TB", "RB"],
  [102, "Jordan Mason", "MIN", "RB"],
  [103, "Wan'Dale Robinson", "TEN", "WR"],
  [104, "Kyle Monangai", "CHI", "RB"],
  [105, "Patrick Mahomes", "KC", "QB"],
  [106, "Alec Pierce", "IND", "WR"],
  [107, "Jaxson Dart", "NYG", "QB"],
  [108, "Jake Ferguson", "DAL", "TE"],
  [109, "Jordan Addison", "MIN", "WR"],
  [110, "Jayden Reed", "GB", "WR"],
  [111, "Jacory Croskey-Merritt", "WAS", "RB"],
  [112, "Travis Kelce", "KC", "TE"],
  [113, "Brock Purdy", "SF", "QB"],
  [114, "Aaron Jones", "MIN", "RB"],
  [115, "Bo Nix", "DEN", "QB"],
  [116, "Brandon Aubrey", "DAL", "K"],
  [117, "Jakobi Meyers", "JAX", "WR"],
  [118, "Myles Garrett", "CLE", "DE"],
  [119, "Jordyn Brooks", "MIA", "LB"],
  [120, "KC Concepcion", "CLE", "WR"],
  [121, "Jared Goff", "DET", "QB"],
  [122, "Keenan Allen", "IND", "WR"],
  [123, "Isaiah Likely", "NYG", "TE"],
  [124, "Dallas Goedert", "PHI", "TE"],
  [125, "Romeo Doubs", "NE", "WR"],
  [126, "Matthew Golden", "GB", "WR"],
  [127, "Kyler Murray", "MIN", "QB"],
  [128, "Xavier Worthy", "KC", "WR"],
  [129, "Chris Rodriguez", "JAX", "RB"],
  [130, "Dalton Kincaid", "BUF", "TE"],
  [131, "Jordan Love", "GB", "QB"],
  [132, "Aidan Hutchinson", "DET", "DE"],
  [133, "Jalen Coker", "CAR", "WR"],
  [134, "Baker Mayfield", "TB", "QB"],
  [135, "Carson Schwesinger", "CLE", "LB"],
  [136, "Keaton Mitchell", "LAC", "RB"],
  [137, "Tyler Allgeier", "ARI", "RB"],
  [138, "Khalil Shakir", "BUF", "WR"],
  [139, "Jack Campbell", "DET", "LB"],
  [140, "Mike Washington", "LV", "RB"],
  [141, "Mark Andrews", "BAL", "TE"],
  [142, "Blake Cashman", "MIN", "LB"],
  [143, "Tyler Shough", "NO", "QB"],
  [144, "Woody Marks", "HOU", "RB"],
  [145, "Jordyn Tyson", "NO", "WR"],
  [146, "Tyrone Tracy", "NYG", "RB"],
  [147, "Deebo Samuel", "SF", "WR"],
  [148, "Maxx Crosby", "LV", "DE"],
  [149, "Will Anderson", "HOU", "DE"],
  [150, "Tyjae Spears", "TEN", "RB"],
  [151, "Rashid Shaheed", "SEA", "WR"],
  [152, "Ka'imi Fairbairn", "HOU", "K"],
  [153, "Cyrus Allen", "KC", "WR"],
  [154, "Malik Willis", "MIA", "QB"],
  [155, "Zach Charbonnet", "SEA", "RB"],
  [156, "Jeffery Simmons", "TEN", "DT"],
  [157, "Isiah Pacheco", "KC", "RB"],
  [158, "Jauan Jennings", "MIN", "WR"],
  [159, "Brenton Strange", "JAX", "TE"],
  [160, "Nick Bolton", "KC", "LB"],
  [161, "Juwan Johnson", "NO", "TE"],
  [162, "Roquan Smith", "BAL", "LB"],
  [163, "Denzel Boston", "CLE", "WR"],
  [164, "Alvin Kamara", "NO", "RB"],
  [165, "Terrance Ferguson", "LAR", "TE"],
  [166, "Tre Tucker", "LV", "WR"],
  [167, "Oronde Gadsden", "LAC", "TE"],
  [168, "Foyesade Oluokun", "JAX", "LB"],
  [169, "Dylan Sampson", "CLE", "RB"],
  [170, "Kayshon Boutte", "HOU", "WR"],
  [171, "Danielle Hunter", "HOU", "DE"],
  [172, "Jason Myers", "SEA", "K"],
  [173, "Chig Okonkwo", "WAS", "TE"],
  [174, "Tank Bigsby", "PHI", "RB"],
  [175, "Cam Little", "JAX", "K"],
  [176, "Omar Cooper", "NYJ", "WR"],
  [177, "Jalen Nailor", "LV", "WR"],
  [178, "Brian Robinson", "ATL", "RB"],
  [179, "Cameron Dicker", "LAC", "K"],
  [180, "Jalen McMillan", "TB", "WR"],
  [181, "Malik Washington", "MIA", "WR"],
  [182, "Fred Warner", "SF", "LB"],
  [183, "Braelon Allen", "NYJ", "RB"],
  [184, "Jonah Coleman", "DEN", "RB"],
  [185, "Kenyon Sadiq", "NYJ", "TE"],
  [186, "Dalton Schultz", "HOU", "TE"],
  [187, "Tremaine Edmunds", "NYG", "LB"],
  [188, "Kaelon Black", "SF", "RB"],
  [189, "Tyler Loop", "BAL", "K"],
  [190, "Alex Singleton", "DEN", "LB"],
  [191, "Jake Bates", "DET", "K"],
  [192, "Cooper DeJean", "PHI", "S"],
  [193, "Ernest Jones", "SEA", "LB"],
  [194, "T.J. Hockenson", "MIN", "TE"],
  [195, "Zack Baun", "PHI", "LB"],
  [196, "Jared Verse", "CLE", "LB"],
  [197, "C.J. Stroud", "HOU", "QB"],
  [198, "Justice Hill", "BAL", "RB"],
  [199, "Harrison Mevis", "LAR", "K"],
  [200, "Hunter Henry", "NE", "TE"],
  [201, "Jerry Jeudy", "CLE", "WR"],
  [202, "Jamien Sherwood", "NYJ", "LB"],
  [203, "Daniel Jones", "IND", "QB"],
  [204, "Ryan Flournoy", "DAL", "WR"],
  [205, "Tank Dell", "HOU", "WR"],
  [206, "Ray Davis", "BUF", "RB"],
  [207, "Cam Ward", "TEN", "QB"],
  [208, "Cedric Gray", "TEN", "LB"],
  [209, "Budda Baker", "ARI", "S"],
  [210, "Dontayvion Wicks", "PHI", "WR"],
  [211, "Austin Booker", "CHI", "DE"],
  [212, "Isaac TeSlaa", "DET", "WR"],
  [214, "Bryce Young", "CAR", "QB"],
  [215, "Tre' Harris", "LAC", "WR"],
  [217, "Calvin Ridley", "TEN", "WR"],
  [219, "Nick Bosa", "SF", "DE"],
  [220, "Kimani Vidal", "LAC", "RB"],
  [221, "Adonai Mitchell", "NYJ", "WR"],
  [222, "Nate Landman", "LAR", "LB"],
  [223, "Eddy Pineiro", "SF", "K"],
  [224, "Quay Walker", "LV", "LB"],
  [225, "Derwin James", "LAC", "S"],
  [226, "Josh Hines-Allen", "JAX", "DE"],
  [227, "Kyle Hamilton", "BAL", "S"],
  [228, "Evan McPherson", "CIN", "K"],
  [229, "Edgerrin Cooper", "GB", "LB"],
  [230, "Harrison Butker", "KC", "K"],
  [231, "AJ Barner", "SEA", "TE"],
  [232, "Cooper Kupp", "SEA", "WR"],
  [233, "Nick Cross", "WAS", "S"],
  [234, "Emmett Johnson", "KC", "RB"],
  [235, "James Conner", "ARI", "RB"],
  [236, "Ja'Kobi Lane", "BAL", "WR"],
  [237, "DeForest Buckner", "IND", "DT"],
  [238, "Zaire Franklin", "GB", "LB"],
  [239, "Derrick Brown", "CAR", "DE"],
  [240, "Talanoa Hufanga", "DEN", "S"],
  [241, "Greg Dulcich", "MIA", "TE"],
  [242, "Jacoby Brissett", "ARI", "QB"],
  [243, "Darnell Mooney", "NYG", "WR"],
  [244, "T.J. Edwards", "CHI", "LB"],
  [245, "Chase Young", "NO", "DE"],
  [246, "Demario Davis", "NYJ", "LB"],
  [247, "Devin Bush", "CHI", "LB"],
  [248, "Tyler Bass", "BUF", "K"],
  [249, "Chamarri Conner", "KC", "S"],
  [250, "Robert Spillane", "NE", "LB"],
  [251, "Zachariah Branch", "ATL", "WR"],
  [252, "Brian Burns", "NYG", "DE"],
  [253, "Sean Tucker", "TB", "RB"],
  [254, "Aaron Rodgers", "PIT", "QB"],
  [255, "Pat Freiermuth", "PIT", "TE"],
  [256, "Caleb Douglas", "MIA", "WR"],
  [257, "Travis Hunter", "JAX", "WR"],
  [258, "Jordan James", "SF", "RB"],
  [259, "Jalen Ramsey", "PIT", "S"],
  [260, "Troy Franklin", "DEN", "WR"],
  [261, "George Holani", "SEA", "RB"],
  [262, "Cade Otton", "TB", "TE"],
  [263, "Kevin Byard", "NE", "S"],
  [264, "Cameron Heyward", "PIT", "DT"],
  [265, "Evan Engram", "DEN", "TE"],
  [266, "DeMarcus Lawrence", "SEA", "DE"],
  [267, "Malachi Fields", "NYG", "WR"],
  [268, "Gunnar Helm", "TEN", "TE"],
  [269, "Cairo Santos", "CHI", "K"],
  [270, "Daiyan Henley", "LAC", "LB"],
  [271, "Jessie Bates", "ATL", "S"],
  [272, "Xavier McKinney", "GB", "S"],
  [273, "Tre'von Moehrig", "CAR", "S"],
  [274, "Patrick Queen", "PIT", "LB"],
  [275, "Colby Parkinson", "LAR", "TE"],
  [276, "Emanuel Wilson", "SEA", "RB"],
  [277, "Brayden Narveson", "GB", "K"],
  [278, "Drue Tranquill", "KC", "LB"],
  [279, "Kamari Lassiter", "HOU", "CB"],
  [280, "Kaytron Allen", "WAS", "RB"],
  [281, "Mike Gesicki", "CIN", "TE"],
  [282, "Will Reichard", "MIN", "K"],
  [283, "Kirk Cousins", "LV", "QB"],
  [284, "Rashod Bateman", "BAL", "WR"],
  [286, "Divine Deablo", "ATL", "LB"],
  [287, "Montez Sweat", "CHI", "DE"],
  [289, "Nicholas Singleton", "TEN", "RB"],
  [291, "Jaylen Wright", "MIA", "RB"],
  [292, "Andy Borregales", "NE", "K"],
  [293, "Mack Wilson", "ARI", "LB"],
  [294, "Emari Demercado", "DAL", "RB"],
  [295, "Samaje Perine", "CIN", "RB"],
  [296, "Fernando Mendoza", "LV", "QB"],
  [297, "Germie Bernard", "PIT", "WR"],
  [298, "Chase McLaughlin", "TB", "K"],
  [299, "Chris Boswell", "PIT", "K"],
  [300, "Travon Walker", "JAX", "DE"],
  [301, "Jordan Battle", "CIN", "S"],
  [302, "Geno Smith", "NYJ", "QB"],
  [304, "Abdul Carter", "NYG", "LB"],
  [305, "Pat Bryant", "DEN", "WR"],
  [306, "Kaden Elliss", "NO", "LB"],
  [307, "Nnamdi Madubuike", "BAL", "DT"],
  [308, "Chris Bell", "MIA", "WR"],
  [309, "Wil Lutz", "DEN", "K"],
  [310, "Jack Bech", "LV", "WR"],
  [311, "Jeremy Chinn", "LV", "S"],
  [312, "Najee Harris", "NYG", "RB"],
  [313, "Michael Penix", "ATL", "QB"],
  [314, "Shedeur Sanders", "CLE", "QB"],
  [315, "Jalen Redmond", "MIN", "DT"],
  [316, "Deshaun Watson", "CLE", "QB"],
  [317, "Jake Tonges", "SF", "TE"],
  [318, "Kamren Curl", "LAR", "S"],
  [319, "Eric Wilson", "MIN", "LB"],
  [320, "Jordan Davis", "PHI", "DT"],
  // Additional bench-level depth (backup QBs / RB3-4 / WR5-6 / streamer TEs)
  // to round the offline dataset out past 300 fantasy-relevant players.
  [321, "Sam Darnold", "SEA", "QB"],
  [322, "Justin Fields", "NYJ", "QB"],
  [323, "Anthony Richardson", "IND", "QB"],
  [324, "J.J. McCarthy", "MIN", "QB"],
  [325, "Spencer Rattler", "NO", "QB"],
  [326, "Zamir White", "LV", "RB"],
  [327, "Roschon Johnson", "CHI", "RB"],
  [328, "Ty Chandler", "MIN", "RB"],
  [329, "Miles Sanders", "DAL", "RB"],
  [330, "Craig Reynolds", "DET", "RB"],
  [331, "Antonio Gibson", "NE", "RB"],
  [332, "Zack Moss", "CIN", "RB"],
  [333, "Dameon Pierce", "HOU", "RB"],
  [334, "Marquise Brown", "KC", "WR"],
  [335, "Elijah Moore", "BUF", "WR"],
  [336, "Curtis Samuel", "BUF", "WR"],
  [337, "Demarcus Robinson", "SF", "WR"],
  [338, "Jalen Tolbert", "DAL", "WR"],
  [339, "Xavier Legette", "CAR", "WR"],
  [340, "Ricky Pearsall", "SF", "WR"],
  [341, "Adam Thielen", "CAR", "WR"],
  [342, "Noah Fant", "CIN", "TE"],
  [343, "Cole Kmet", "CHI", "TE"],
  [344, "Zach Ertz", "WAS", "TE"],
  [345, "Tyler Conklin", "LAC", "TE"],
  [346, "Will Dissly", "LAC", "TE"],
  [347, "Michael Mayer", "LV", "TE"],
  [348, "Elijah Arroyo", "SEA", "TE"],
  [349, "Ben Sinnott", "WAS", "TE"],
  [350, "Grady Jarrett", "ATL", "DT"],
];

// Team defense (D/ST) consensus rank order, 2026 preseason.
export const DST_ORDER = [
  "HOU", "DEN", "SEA", "LAR", "PHI", "MIN", "LAC", "BAL", "NE", "PIT",
  "JAX", "GB", "CLE", "BUF", "KC", "DET", "NO", "SF", "ATL", "TB",
  "CAR", "CHI", "NYG", "IND", "TEN", "MIA", "DAL", "LV", "WAS", "NYJ",
  "CIN", "ARI",
];

export const TEAM_NAMES = {
  ARI: "Arizona Cardinals", ATL: "Atlanta Falcons", BAL: "Baltimore Ravens",
  BUF: "Buffalo Bills", CAR: "Carolina Panthers", CHI: "Chicago Bears",
  CIN: "Cincinnati Bengals", CLE: "Cleveland Browns", DAL: "Dallas Cowboys",
  DEN: "Denver Broncos", DET: "Detroit Lions", GB: "Green Bay Packers",
  HOU: "Houston Texans", IND: "Indianapolis Colts", JAX: "Jacksonville Jaguars",
  KC: "Kansas City Chiefs", LAC: "Los Angeles Chargers", LAR: "Los Angeles Rams",
  LV: "Las Vegas Raiders", MIA: "Miami Dolphins", MIN: "Minnesota Vikings",
  NE: "New England Patriots", NO: "New Orleans Saints", NYG: "New York Giants",
  NYJ: "New York Jets", PHI: "Philadelphia Eagles", PIT: "Pittsburgh Steelers",
  SEA: "Seattle Seahawks", SF: "San Francisco 49ers", TB: "Tampa Bay Buccaneers",
  TEN: "Tennessee Titans", WAS: "Washington Commanders",
};

// 2026 NFL bye weeks by team, per league schedule release.
export const BYE_WEEKS = {
  CAR: 5, KC: 5,
  CIN: 6, DET: 6, MIA: 6, MIN: 6,
  BUF: 7, JAX: 7, LAC: 7, WAS: 7,
  HOU: 8, NO: 8, NYG: 8, SF: 8,
  PIT: 9, TEN: 9,
  CHI: 10, DEN: 10, PHI: 10, TB: 10,
  ATL: 11, CLE: 11, GB: 11, LAR: 11, NE: 11, SEA: 11,
  BAL: 13, IND: 13, LV: 13, NYJ: 13,
  ARI: 14, DAL: 14,
};
